### ISSUE TITLE
Pure Lua vs. heavy lifting in Rust?

### ISSUE THREAD

**Issue by alerque** [alerque/fluent-lua#2]
Probably the most significant design choice out of the gate will be to decide whether to

* write a pure Lua implementation from scratch, probably using a PEG grammar, or
* leverage an existing implementation such as [Rust](https://github.com/projectfluent/fluent-rs) to do the parsing.

Either way the end result should be a usable Lua API, but what are the pros and cons of these two approaches? Is Rust even an option? Will [rlua](https://github.com/kyren/rlua) cut the mustard?

I assume the [lua](https://crates.io/crates/lua) crate is bindings for the other direction than we would need here, as is [hlua](https://crates.io/crates/hlua). What about [rust_lua_ffi](https://github.com/distil/rust_lua_ffi)?

**Comment by alerque** [comment]
Thanks @catwell. That's probably excellent advice — and I'll probably regret ignoring it.

I looked into the Rust binding situation and it's certainly possible, but given that some of my own personal use cases are going to have a hard time with the compiled Rust dependency I'm moving ahead with a pure Lua solution starting with an PEG grammar (using LPEG via luaepnf, see #3) and then of course re-inventing the wheel as far as the rest of the APIs go too. Other than a bit of a ticklish nightmare avoiding the way PEG grammars can't have empty loops and the [Fluent EBNF](https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf) I'm working from assumes the possibility of matching EOFs all over the place inside empty loops — all is going well.

By the way, finding this project on a mailing list on which it's never been mentioned is some next level acrobatics! Is there an announcement list for new Lua Rocks postings or something like that?

**Comment by catwell** [comment]
Ha, sorry, maybe I was wrong and found it elsewhere, like on the LuaRocks Gutter!

**Comment by alerque** [comment]
@catwell That makes more sense, I did mention it in there.

By the way the first draft of the PEG grammar is done. It parses everything in the upstream test fixture set (I don't know if it's all right yet because the ASTs aren't comparable yet, but spot checking it looks like it's catching most stuff). I was expecting that to be the hard part, and it wasn't that bad in the end. I'm hoping the rest of the API and handling of all the data now that it's parsed won't be worse than I was expecting.
